version: '3.9'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jobmatcher
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    networks:
      - backend

  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - '8070:8080'
    depends_on:
      - db
    networks:
      - backend
    command: ["php", "-S", "0.0.0.0:8080", "-t", "/var/www/html", "/var/www/html/index.php", "--", "--theme", "nette"]
    volumes:
      - ./adminer-nette.css:/var/www/html/adminer.css:ro
volumes:
  db_data:

networks:
  backend:
    driver: bridge
