apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobmatcher
spec:
  selector:
    matchLabels:
      app: jobmatcher
  template:
    metadata:
      labels:
        app: jobmatcher
    spec:
      imagePullSecrets:
        - name: github-regcred
      containers:
        - name: jobmatcher
          image: ghcr.io/makokhavictor/job-matcher:latest
          envFrom:
            - secretRef:
                name: jobmatcher-secrets
          ports:
            - containerPort: 3000